system:
  title: '初めてのキャンプ'
  url: 'http://first-camping.ddo.jp/'
  bbs_url: 
  trello_url: 
  google_form_url: 
  official_twitter_id: 'newburu'
  description: '初めてキャンプをする人向けのサービス'
  description_smartphone: '初めてのキャンプ！！'
  hashtag: '初めてのキャンプ'
  keywords: ['Twitter', 'キャンプ', '初めてのキャンプ']
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet'
    share_url: 'http://twitter.com/share'
  facebook:
    share_url: 'https://www.facebook.com/share.php'
  line:
    share_url: 'https://social-plugins.line.me/lineit/share'
  mail:
    share_url: 'mailto:'
  default:
    user_name: 名無しさん
  const:
    on_str: 'on'
    off_str: 'off'